### ISSUE TITLE
Tracking: Create app that can inspect the status of the system

### ISSUE THREAD

**Issue by bradjc** [tock/tock#1047]
We talked about this briefly on a call, but the general idea is to create a userspace "manager" process that can at least query the current state of the system: how many processes are running: how many processes have faulted, etc.

- [x] Come up with a name for the module in the kernel that would support this.
- [x] Add support for capabilities because this info shouldn't be widely available.
- [x] Improve `AppId` so that there is a unique identifier per process. This will provide some mechanism for the userspace app to be able to refer to processes on the board. (#1588)
- [x] Create a module in the kernel crate that provides functions for querying this data.
- [x] Create a capsule that provides this info to userspace.
- [x] Implement some sort of restriction so only some processes can call these special syscalls.
- [ ] Implement an app that queries the values and provides it over some sort of network (15.4/BLE).
