### ISSUE TITLE
Tracking: Implement serial over USB

### ISSUE THREAD

**Issue by bradjc** [tock/tock#1048]
Not requiring an FTDI chip would be awesome, and since modern MCUs have USB support this is at least plausible on our current platforms.

- [ ] Implement the CDC ACM profile for USB. #1902
- [ ] See if our USB code can be ported to the nRF52.
- [ ] Verify that Tockloader can work with the CDC port. #1902

**Comment by bradjc** [comment]
This will be very important to support the https://store.arduino.cc/usa/nano-33-ble board correctly.
