### ISSUE TITLE
Tracking: New Rust Features to Use

### ISSUE THREAD

**Issue by bradjc** [tock/tock#1083]
This lists new Rust features that we want the next time we update the nightly version (or are available now).

- [ ] Be explicit about imports that exist only to bring traits into scope.
    With https://github.com/rust-lang/rust/issues/48216, traits can be brought into scope with `use mycrate::traitholder as _`, which makes it clearer that nothing from that module is used directly.
- [x] Remove the homemade `AtomicUsize` in deferred_call.rs.
    With https://github.com/rust-lang/rust/pull/51953, even though the m0 doesn't support CaS instructions, it does support enough for our deferred call mechanism to work.
- [x] Use LLVM 7
    https://github.com/rust-lang/rust/pull/51966 (merged)
- [ ] Use new math implementation that should simplify common/math.rs.
    https://github.com/japaric/libm

**Comment by bradjc** [comment]
Eh, using Rust 2018 is a pretty good step towards this.
