### ISSUE TITLE
Tracking: Revisit what is exported from the kernel crate

### ISSUE THREAD

**Issue by bradjc** [tock/tock#1088]
The kernel crate contains many unsafe and "dangerous" (i.e. they must be used carefully or they invalidate Tock safety guarantees) data structures. We need to be careful with exactly how these are exposed outside of the kernel crate.

- [x] Restrict which modules are public. (#955)
- [x] Make internal use only functions limited to just the kernel crate (using the `crate` modifier).
- [ ] Evaluate and justify that functions which wrap a single `unsafe` call are safe.
- [ ] Mark only functions which violate Rust type safety as `unsafe`.
- [ ] Require a capability to call all "dangerous" functions.
  - [x] Add capabilities feature.

**Comment by bradjc** [comment]
I came across an instance in Tock where this might be complicated: capsules can get access to `process` objects by calling `kernel.process_each_capability()`. Now, iterating the list of processes requires a capability, but once they have the process object they can call any function in the `ProcessType` trait (that isn't marked unsafe).

**Comment by phil-levis** [comment]
> I came across an instance in Tock where this might be complicated: capsules can get access to `process` objects by calling `kernel.process_each_capability()`. Now, iterating the list of processes requires a capability, but once they have the process object they can call any function in the `ProcessType` trait (that isn't marked unsafe).

This was intentional: the idea was that the ProcessManagementCapability meant a (non-crate) module could access and manage processes. If we want to have finer grained control, we can add individual capabilities to certain `ProcessType` operations, or break up the trait into smaller traits with narrower functionality. The point was to make it possible for capsules (e.g., the process console) to be able to access and interact with processes.

**Comment by bradjc** [comment]
2.0 seems like an opportunity to actually handle this issue.

Proposal: we remove all `pub use crate::` lines from kernel/src/lib.rs and use pub and pub(crate) modifiers in each file to determine visibility. We make special exceptions for objects that we don't want to be namespaced (perhaps `Kernel`).

https://github.com/tock/tock/blob/fb130b4b668a1e60514da85fc4a94a05cd840797/kernel/src/lib.rs#L112

**Comment by hudson-ayers** [comment]
Why do we have to remove the `pub use` declarations for that? If you tried to mark `AppId` as `pub(crate)` instead of the current `pub` it would fail to compile (you can't `pub use` a non-`pub` struct).

And I don't see a ton of benefit to exposing the internal kernel file structure to capsules, it just makes it a pain to rename files within the kernel, and adds verbosity to imports.

Maybe I am missing something?

**Comment by bradjc** [comment]
The reasons I have are:
1. It would force us to think explicitly about namespacing. Right now we have done it in a very ad-hoc manner. I think our current approach is confusing in some cases, e.g. what does `kernel::Private` mean? We also sometimes use paths, and sometimes don't, and I don't think we have a rationale for when or why we do.

    I agree that we should have some `pub use`, for example `kernel::Kernel` and `kernel::ErrorCode` make sense to me.
2. I think the verbosity is a good thing. For example, having an explicit record that `CoopProcessNode` is related to scheduling seems advantageous for someone reading the code.

What I would _actually_ prefer is exporting everything explicitly from lib.rs using the `pub mod {` syntax in lib.rs, like what we are doing for `procs`. That would give us flexibility with grouping and not relying on file names. However, since rust does not let you use the same name as a filename, this isn't really feasible (and is why we have `procs` right now...).

**Comment by bradjc** [comment]
#2659 may not be perfect, but I think it's better than what we had.

Closing this at this point.
