### ISSUE TITLE
Tracking: Support RISC-V

### ISSUE THREAD

**Issue by bradjc** [tock/tock#1135]
### Update June 2020

Tock includes preliminary RISC-V support, and several boards that are RISC-V based. There are a few lingering TODOs to get reasonably comparable support with Cortex-M.

# Tracking

- [x] Add support for risc-v (at least riscv32imac) in nightly rust. (https://github.com/rust-lang-nursery/embedded-wg/issues/36, https://github.com/rust-lang/rust/pull/52787)
- [x] Simplify binutils for riscv32. Ideally the LLVM tools that ship with rust will work. But if not we need some way to distribute riscv32-ld and riscv32-objcopy that doesn't rely on users building from source.
  - [x] Upstream lld support for riscv: https://github.com/riscv/riscv-lld/issues/1. First PR is in! https://github.com/llvm-mirror/lld/commit/9e54d159934e86f7a83c58ed21341bc89ff2bd2b
- [x] Develop support for risc-v in Tock.
  - [x] Add a RV32I arch crate. #1323
  - [x] Create a HiFive1 board in `/boards`. PR: #1317 
  - [x] Create an `arty-e21` board for running the E21 core on the ARTY FPGA. #1323
  - [x] Implement a driver for the Physical Memory Protection (PMP) peripheral.
  - [x] Implement a driver for the CLIC peripheral. #1323
  - [x] Implement `UserlandKernelBoundary` for risc-v. This would enable context switches to userland. #1323
  - [x] Implement a systick replacement for providing timeslices for apps.
  - [x] Support the HiFive1(b) board. https://github.com/tock/tock/tree/hifive1b
  - [x] Add better fault printing and debugging support.
- [x] Add support to Tockloader for loading code on risc-v boards. It seems like they use openocd, but unfortunately it seems to be a custom fork. https://github.com/riscv/riscv-wiki/wiki/RISC-V-Software-Status#openocd Status: this exists for arty-e21, pending for HiFive1.
- [ ] Add links to external documentation. Make it easier for developers to find information about the ISA, peripherals, and sifive-specific peripherals.
- [ ] Support userland c apps
  - [x] Update crt0.c and tock.c to support risc-v. On libtock-c: `make RISCV=1`.
  - [ ] Get PIC working. This seems like it might be a ways off: https://github.com/riscv/riscv-gcc/issues/158
    - [x] Alternative: use N x K linking https://github.com/tock/libtock-c/issues/63
  - [ ] Verify various more advanced apps work.

# Intro

This RISC-V architecture continues to gain momentum, and having Tock support risc-v boards seems quite feasible. With the [embedded version still in development](https://en.wikipedia.org/wiki/RISC-V#ISA_Base_and_Extensions), it seems like Tock could be a leading embedded OS for risc-v platforms. Also, supporting multiple architectures would demonstrate the Tock architecture flexibility.

**Comment by bradjc** [comment]
The development for this is happening in the https://github.com/tock/tock/tree/riscv branch.

So far:
- [x] riscvimac crate
- [x] basic e310x chip
- [x] basic hifive1 board
- [x] UART TX working
- [x] GPIO set working
- [ ] GPIO interrupts (untested)
- [ ] RTC implementation
- [ ] alarm hil implementation

**Comment by bradjc** [comment]
I'm having trouble figuring out how to implement the context switch for Tock. Now the HiFive E310 chip only has M-mode, which means we won't have the application isolation we want, but it will serve as a proof of concept.

I think there are three primary operations to make context switching happen:

### Switching to userland the first time

After the kernel is setup and the processes are loaded, the kernel must switch to the first process. I believe this can be done by setting the `mepc` register and calling the `MRET` instruction:

```asm
// Set mepc to the starting PC of the app.
// Here it is assuming the app entry point is at address 0x20c00000.
lui a0, %hi(0x20c00000)
addi a0, a0, %lo(0x20c00000)
csrw 0x341, a0

// Now go to what is in mepc.
mret
```

The `mret` instruction changes the privilege level before it executes code at the new location. This doesn't matter on a platform with only M mode, but it sets up an easier transition to a chip with user mode.

### Returning from the app to the kernel.

To call a syscall the app has to return control to the kernel. I believe the app can do this with the `ECALL` instruction.


### Handling the syscall and returning to the app

When the app calls the `ECALL` instruction that causes the trap handler to execute (which is configured by setting the `mtvec` register) with `mcause` set to "Environment call from M-mode". The trap handler can save the register state and handle whatever else it needs to, but it also needs to return execution to the instruction after the jump to the userland app. That is, the `switch_to()` function needs to be able to return. This is what I am unsure of how to do.

Using the `MRET` instruction at this point would, if I understand correctly, switch back to the app.

**Comment by anmolsahoo25** [comment]
> ECALL and EBREAK cause the receiving privilege mode’s epc register to be set to the address of
> the ECALL or EBREAK instruction itself, not the address of the following instruction.

So based on this, we would have to set mepc to mepc + 4 and then mret which will then return to the userland app, if that is what is required. Setting mepc to the next instruction address is necessary.

**Comment by DieracDelta** [comment]
Is this still in development on the riscv branch? If so, has anyone tried to test this on the riscv board? Did you manage to get openocd working well enough to actually load tock without userland/context switching onto the board?
