### ISSUE TITLE
Tracking: Migrating away from CC26xx crate

### ISSUE THREAD

**Issue by alevy** [tock/tock#1137]
We've already begun duplicating modules and functionality in the CC26x2 crate where the hardware differs slightly, and our goal is to continue doing so until the CC26XX crate is redundant and we can remove it.

The impetus for this tracking issue is that the CC26xx covers a broad spectrum of chips that are subtly dissimilar from each others in way that are not documented well by the TI datasheets. We currently on have plans to support _one_ of the sub-families (the CC26x2/CC13x2) in tree, while the older series lacks an MPU, so isn't a great fit for Tock long term.

Moreover, some of what _is_ implemented in the CC26xx crate is not quite correct in some ways (e.g. blocking implementations of asynchronous calls). Because of this, some of the modules in CC26XX need to be re-implemented or updated, not just moved.

There is currently [a separate repo](/tock/tock-sensortag) with a fair bit of support for the CC26x0, which will continue to exist, at least for posterity (and will live on in this repo by me copying a good chunk of the code from it for the CC26x2).

- [x] PRCM (#1119)
- [x] RTC (#1119)
- [x] AON (#1119)
- [X] IOC (#1158)
- [x] UART (#1156, but still want DMA)
- [x] TRNG
- [X] GPIO (#1158)
- [ ] Migrate crate to sensortag repo
- [ ] After migrating, we should plan to unify how power domain control is done in accordance with other boards in the repo (will turn this into more detailed todos when we get there).

Shout out to @cpluss, @filipni for the massive initial effort to support this family in the first place.

**Comment by bradjc** [comment]
Reopen if I'm mistaken, but since the CC26xx crate is gone we have successfully migrated away from it.
