### ISSUE TITLE
Tracking: Enable Loading Apps at Runtime

### ISSUE THREAD

**Issue by bradjc** [tock/tock#1138]
Currently apps are loaded at "programming time" by a tool like Tockloader. This is important functionality for commissioning boards and testing, but the Tock architecture intuitively supports loading or replacing apps at runtime.

While conceptually simple, there are a number of implementation possibilities and a range of different designs that could accomplish this goal. Most notably is what is handled in userspace versus in the kernel (likely as a capsule).

- [x] Provide some kernel introspection functionality. This at minimum would need to provide what flash is available for storing a new app.
- [x] Create an app to get the new app from somewhere. This could be over USB, BLE, 15.4, or something else.
- [x] Create a capsule that supports this app. This would help with writing the app to flash and starting the new app.
  - [x] Need a mechanism to load a new app to the processes array, and to remove a previous app.
- [x] Decide how to handle meeting the MPU rules for platforms.
  - [x] Re-work app length management between elf2tab and tockloader. Tockloader is going to have to gain more knowledge on how to place apps.

**Comment by placrosse** [comment]
I've started a discussion about this on both Slack and the mailing list, as I'd like to pick it up and participate in implementation.
