### ISSUE TITLE
Tracking: Redesign kernel crate internals

### ISSUE THREAD

**Issue by alevy** [tock/tock#1143]
- process.rs
  - This keeps evolving. The changes to make apps restartable caused a number of changes. Many other changes in the kernel require changes (or inform changes) to the process interface.
  - [ ] #1739, and potentially other assumptions apps have while they're running about how they were set up
  - [x] Idea: the stack pointer is really entirely up to the process, and shouldn't be managed in process.rs. Tracking the stack pointer in process.rs is a bit of a legacy from the cortex-m syscall implementation. It can probably be moved entirely into UserlandKernelBoundary if it is needed there. Related to #1257 and #1769.
-  Grants
    - [x] Some changes in #1648.
    - [x] Re-think through the allocator interface. In particular, make sure that capsules cannot allocate grant memory that isn't checked for process liveness before it is used.
        - [ ] It might be good for allocated regions for a grant to use a linked list, so the kernel can keep track of them.
    - [x] Encapsulate the low-level pointer management in process.rs which is where the app's memory can be properly managed. Expose grant regions from process.rs as proper `grant::` types.
- AppSlice
    - [x] More documentation
    - [x] Reason about Rust assumptions / guarantees we must provide: e.g. if an app `allow`s the same region of memory twice, this will result in aliased memory in the kernel
- static ref
    - [x] Updates in ~~#1618~~ #1924
- Platform trait
    - [x] Updates in #1680
    - [x] Consider making all configuration/options from the board down to the kernel go through this trait.

--------

The discussion in #1113 is making quite clear that when I wrote the various parts of the kernel crate it was without putting much thought into how to logically structure it, but to just get something working.

I don't have specific things to track yet, but we should sit down and properly design it, since the ~~mess~~ working version I created is starting to hamper us.

**Comment by bradjc** [comment]
Might consider this commit: 8b392f17f7ac8366dbd8e524946ee0592b2ad928. It changes what must be `mut` in the kernel.

**Comment by bradjc** [comment]
I think this issue has run its course. For 2.0 major re-writes have happened and outstanding issues with grants and alignment have their own issues.
