### ISSUE TITLE
Tracking: SenSys Tutorial

### ISSUE THREAD

**Issue by bradjc** [tock/tock#1173]
Keeping track of what needs to be done for the upcoming tutorial.

- [ ] Provide mechanism to inspect process state. (#1168)
- [ ] Create capsule to provide UDP access to process state. (Phil)
- [ ] Create an app that is broken (likely just a `while(1)` app).

**Comment by phil-levis** [comment]
My work on 2 can be found here: https://github.com/tock/tock/tree/process-control
