### ISSUE TITLE
Tracking: Support Cortex-M with Floating Point

### ISSUE THREAD

**Issue by bradjc** [tock/tock#1246]
Some of the supported MCUs in Tock support floating point operations, but we do not use them because enabling floating point changes the interface between user and kernel modes.

- [ ] Implement `UserspaceKernelBoundary` for cortex-mf.
- [ ] Add a function for enabling floating point support. (#1010)
- [ ] Organize the arch/cortex-m* crates to export the correct functionality.
- [ ] Expand the nrf52 chip.rs so that cortex-m4f is an option.
- [ ] Probably add a new board for the nrf52 that uses floating point support.

**Comment by alistair23** [comment]
https://github.com/tock/tock/pull/2348 should do a few of the bullet points
