### ISSUE TITLE
Tracking: Support multiple static apps in Tock

### ISSUE THREAD

**Issue by rajivr** [tock/tock#1283]
- [x] Add support in the TBF header for apps to specify where their RAM region must begin.
- [x] Add support in elf2tab for adding the TBF headers. This is merged, but not released quite yet (June 2020).
- [x] Add support for the kernel checking that addresses are met.
- [ ] Updated loading processes so that the kernel uses the correct memory locations. (#1928)

@jrvanwhy recently added statically linked app support to `libtock-rs`.

The limitation right now is that we do not have a good way to support multiple statically linked apps. I was wondering if there was interest upstream for supporting multiple statically linked apps?

My motivation for being in favor of supporting multiple statically linked apps is as follows.

1. Dynamic Apps requires `ROPI-RWPI` which is not fully supported by Rust for ARM M profile targets

2. Even if Rust on ARM M profile targets eventually gets `ROPI-RWPI` support, there is no guarantee that other Rust embedded targets would have a position independent model similar to `ROPI-RWPI` that would be suitable for Tock Apps

One argument against adding support for statically linked app could be,

- In Tock, it is currently possible to update Tock Apps independently, as long as syscall ABI is the same. If upstream considers this a critical feature of Tock, then statically linked Apps will not allow for this possibility 

While the following list is not meant to be exhaustive, I want to capture the potential changes that we might need in order to properly support multiple statically linked Apps.

#### TBF Changes (might require a version bump)

1. Introduce a field to specify if an app is static or a dynamic app

2. For a static app, capture `app_flash_start`, in order to indicate where in flash the TBF file would be placed.

3. For a static app, capture `app_memory_start` in order to indicate where in memory we expect App's SRAM region to start.

#### Kernel MPU changes

1. Introduce `allocate_region_static` with a signature similar to

```
    fn allocate_region_static(
        &self,
        unallocated_memory_start: *const u8,
        unallocated_memory_size: usize,
        app_flash_start: usize,
        app_flash_size: usize,
        permissions: Permissions,
        config: &mut Self::MpuConfig,
    ) -> Option<Region> { ... }
```

where `app_flash_size` would be same as existing `app_flash_size` in `process.rs` which is derived from `tbf_header.get_total_size()`.

2. Introduce `allocate_app_memory_region_static` with a signature similar to

```
    fn allocate_app_memory_region_static(
        &self,
        unallocated_memory_start: *const u8,
        unallocated_memory_size: usize,
        app_ram_start: usize,
        app_ram_size: usize,
        initial_app_memory_size: usize,
        permissions: Permissions,
        memory_type: MemoryType,
        config: &mut Self::MpuConfig,
    ) -> Option<(*const u8, usize)> { ... }
```

Unlike `allocate_app_memory_region`, there is *no* `initial_kernel_memory_size`. Process accessible memory would be from `app_ram_start` to `app_ram_start + initial_app_memory_size`. Unused + Grant would be from `app_ram_start + initial_app_memory_size` to `app_ram_start + app_ram_size`.

Right now the total app kernel memory is derived from `kernel_heap_len` (from `elf2tbf`) plus `initial_kernel_memory_size` (from `Process::create`). This leads to a situation where end of process memory is not predictable.

_We need to have predictable end of process memory, in order to specify in the linker file, the address of the start of memory for the next app._

For a static app, move the `initial_kernel_memory` into memory specified by `kernel_heap_len`. For static app, the developer will be responsible for allocating sufficient memory for `initial_kernel_memory` and any additional kernel grant memory that drivers might use.

Please let me know your thoughts!

**Comment by bradjc** [comment]
We now have support in libtock-c for easily linking to multiple addresses, elf2tab handles this well, and the kernel can check that an app is at the correct address. There are open PRs (https://github.com/tock/elf2tab/pull/24 and #1928) to make this even better.
