### ISSUE TITLE
Tracking: Deny warnings for documentation builds

### ISSUE THREAD

**Issue by ppannuto** [tock/tock#1334]
Ideally, CI would reject patches that introduce documentation warnings. This has been on my wishlist for a little while, but now it seems like nearly all of the prior issues have been resolved. 

There's one open upstream issue currently preventing this: https://github.com/rust-lang/rust/issues/62184 -- leaving this here as a tracker to follow.

- [ ] Merge in https://github.com/rust-lang/rust/issues/62184
- [ ] Figure out how to fix favicon / logo more generally (here's a start https://github.com/tock/tock/tree/doc-updates)

**Comment by ppannuto** [comment]
Also on my queue of doc cleanups, prettifying things a bit:

 - [ ] Figure out how to fix favicon / logo more generally (here's a start https://github.com/tock/tock/tree/doc-updates)
