### ISSUE TITLE
Tracking: Revamp TBF Parsing

### ISSUE THREAD

**Issue by bradjc** [tock/tock#1465]
- [x] Break parsing function `parse_and_validate_tbf_header()` into multiple smaller functions that take slices to what they are working on. (#1480)
  ~~- [ ] Make the actually `unsafe` operations clearly marked. However, the base function is still unsafe.~~
- [x] Add a TLV for specifying the memory address the process _must_ be assigned. This is needed for the N x K app linking alternative to PIC.
- [x] Move the TBF code to its own crate in `/libraries`.

**Comment by bradjc** [comment]
I'm working on an extension to the TBF format so that elf2tab can specify fixed addresses for processes, and the kernel can verify the resulting address. This won't functionally change much, but will help with debugging and error reporting, since right now address mismatch issues lead to difficult to catch errors.
