### ISSUE TITLE
Tracking: Virtual serial over USB

### ISSUE THREAD

**Issue by brghena** [tock/tock#1893]
Tracking items:

- [x] Implement some sort of check so that the CDC layer doesn't send data before the USB stack is ready.
- [x] Allow boards to configure the `STRINGS` for the CDC descriptors.
- [x] Decide on a VENDOR_ID and PRODUCT_ID.

**Motivation:**
Many news boards with the nRF52840 that would otherwise be great for Tock use the native USB peripheral on the nRF52840 to connect to it. To make use of these boards, Tock should implement a virtual serial interface over this USB peripheral. This could then be used both for debugging at runtime and secondarily for creating a USB bootloader.

**Background:**
Virtual serial ports can be created through the CDC (Communications Device Class) through the ACM (Abstract Control Model) subclass. This requires the use of three endpoints, one `Interrupt IN` for status notifications (referred to as the "communication" interface) and a `Bulk IN` and `Bulk OUT` for actually sending the serial data (referred to collectively as the "data" interface). The descriptors for this class include two interface descriptors, and several class-specific descriptors as shown in the image below. Here's a good article explaining CDC serial ports specifically: http://janaxelson.com/usb_virtual_com_port.htm
and here's general documentation on descriptors (and general USB background): https://www.beyondlogic.org/usbnutshell/usb5.shtml

![vcp_figure2](https://user-images.githubusercontent.com/235448/83300134-48707d80-a1ac-11ea-9430-621127043d88.jpg)

**Existing Works:**
There are several implementations of CDC serial consoles for the nRF52840. Particularly, the [TinyUSB](https://github.com/hathach/tinyusb) implementation seems pretty trustworthy and worth looking at to understand descriptor details and a minimal implementation of the command interface.

[OpenSK](https://github.com/google/OpenSK) also has an implementation of a USB HID class that works with Tock! The code is easiest to look at locally after setting up a repo as it is in a [patch file](https://github.com/google/OpenSK/blob/master/patches/tock/02-usb.patch). `usb_ctap_hid.rs` mostly layers on top of `usbc_client_ctrl.rs`, which layers on top of the USB HIL, although both the `usb_ctap_hid` and `usbc_client_ctrl` make direct calls to the USB HIL. The file creates several descriptors for a single interface.

**Plan:**
Implement a CDC ACM interface for Tock. It should live on top of the existing USB HIL, possibly on top of the `usbc_client_ctrl` interface. A layer on  top of that should provide a UART HIL so USB can be used for a console just like RTT does.

Steps (not necessarily ordered):
- [x] Get existing USB example code working on hardware.
- [x] Adapt example USB code to handle multiple interfaces.
- [x] Implement minimal set of "communication" interface.
- [x] To host (`IN`) data transfer with static string.
- [x] Bi-directional data transfer with an echo application.
- [x] Implement UART HIL.

**Questions:**
- What is the purpose of `usbc_client_ctrl`? Should we be modifying it to allow for multiple interfaces or creating something new based on it?
  -  It handles the default control endpoint (endpoint 0) which is used to send descriptors to the host. It should be expanded to fit a variety of higher layers.
- What "communication" interface commands exist and which do we need to implement? I haven't found a good list anywhere but haven't looked very hard yet.
- How do we debug USB stuff?
  - `lsusb` (on linux) is a good start for seeing lists of descriptors!
  - wireshark can be used to capture USB
