### ISSUE TITLE
[Tracking] Convert from llvm_asm!() to new asm!()

### ISSUE THREAD

**Issue by bradjc** [tock/tock#1923]
With a new `asm!()` [macro in Rust nightly](https://blog.rust-lang.org/inside-rust/2020/06/08/new-inline-asm.html) that has a path to stabilization, we should switch our uses of `llvm_asm` to the new format. This is part of #1654.

- [x] arch/cortex-m
- [x] arch/cortex-m0
- [x] arch/cortex-m3
- [x] arch/cortex-m4
- [x] arch/rv32i
- [x] chips/apollo3
- [x] chips/arty_e21_chip
- [x] chips/earlgrey
- [x] chips/stm32f303xc
- [x] chips/stm32f4xx
- [x] libraries (#1926)

**Comment by gendx** [comment]
This is really great given that inline assembly is likely the main reason to use Rust nightly at the moment. And the new macro seems to be getting quite a bit of traction so we can expect it to stabilize in the medium term.

From a programming point of view this is IMO much cleaner than having to link external `.S` files, and if I understood correctly inline `asm!` also allows the compiler to apply more optimizations than with raw `.S` files being linked blindly at the linker step.

**Comment by alistair23** [comment]
https://github.com/tock/tock/pull/1926 is a step in this direction and I think completes the swap for `libraries/riscv-csr``

**Comment by hudson-ayers** [comment]
With the outstanding PRs merged, there are only 4 uses of `llvm_asm` remaining (ignoring all the uses in `cortex-m0`)

**Comment by lschuermann** [comment]
As indicated in #2308, once that change is in, I'll do the migration of the rest of the `rv32i` crate.

**Comment by bradjc** [comment]
Woo!

```
$ git grep llvm_asm | wc -l
       0
```
