### ISSUE TITLE
Tracking: Release new version of tock-register-interface

### ISSUE THREAD

**Issue by andre-richter** [tock/tock#2579]
Now that https://github.com/tock/tock/pull/2517 has landed, please consider releasing a new version on crates.io.

This will allow me to deprecate https://github.com/rust-embedded/register-rs and refer people to `tock-register-interface` for future use.

Thanks in advance,
Andre

@ppannuto @lschuermann

**Comment by lschuermann** [comment]
Thanks for this tracking issue! Releasing a new version is definitely warranted due to this change, so it has been on my list for some time (rather, poking someone to do it :smile:).

That being said, I still have a few short term todos which I think should be done prior to a release:
- [ ] splitting up the internal structure, such that the interfaces, register types, and helpers are cleanly and semantically separated in different modules (that is already somewhat reflected in Tock's `kernel`-crate re-exports of this library, but should really be done in the library itself)
- [ ] adding a feature-flag to exclude the "default" register types (`ReadOnly`, `ReadWrite`, etc.), allowing this to be used as an interface-only library (following the previous change, essentially just disabling importing the module containing these types). A major advantage is that enabling this feature should then remove all unsafe code from the library. 
- [ ] doing a final pass over the doc-comments, and adding some documentation tests and more usage examples

I have some changes ready locally, and I expect to have all the boxes ticked in 1-2 weeks.

Thanks for your input on this, @andre-richter!

**Comment by ppannuto** [comment]
Acking this thread, and eager for @lschuermann's updates! 

1 and 3 here are definite wins. I felt like there was possibly some unresolved discussion around 2 in the call last Friday, but we can re-examine those questions where there is a concrete proposal to discuss.

**Comment by andre-richter** [comment]
@lschuermann please see https://github.com/tock/tock/pull/1489

**Comment by hnj2** [comment]
Hello, I was wondering what the status of the release is?
According to #2618 it is nearly ready, but if that isn't the case a small version bump of `tock-registers` to `0.6.1` to make #2589 available might be nice for nightly users?

**Comment by lschuermann** [comment]
@hnj2 Sorry for the wait! It seems that the only blocking PR for a release is #2551 and writing a Changelog, and I would've hoped that this is a rather uncontroversial set of changes. However, there seems to be some (entirely valid) discussion around this.

I'm not sure. Depending on what @ppannuto and @bradjc think a point release may be justified as the nightly breakage seems to be a rather pressing issue for the wider community.

v0.6.0 corresponds to 72a1e1ea759359, I'll backport #2589 to that on another branch such that we can create a v0.6.1 point release if @ppannuto agrees.

**Comment by lschuermann** [comment]
Mhm, backporting this puts us in a weird position, as `tock-register-interface` is maintained in the Tock repository: by updating the Rust version, we break a lot of existing code in Tock, so we'd create a point release on something with a very red CI :smile:. It's not really feasible to reconstruct a version of Tock compiling on a newer nightly (2021-05-27) on top of 72a1e1ea759359. Therefore, I've created a commit a892097f57f9c5 (branch [tock-register-interface-v0.6.1](https://github.com/tock/tock/tree/tock-register-interface-v0.6.1)) which is based on 72a1e1ea759359 and only bumps the Rust version + backports the essential change of #2589. `tock-register-interface` seems to work fine, `cargo {check, build, test, doc}` work, but the rest of tock does not. Also, we're then having a point release of `tock-registers` not corresponding to any commit on master and any tag. Let's see what others think.
