### ISSUE TITLE
Tracking: Initial IEEE 802.3 Wired Ethernet and IP support in Tock

### ISSUE THREAD

**Issue by lschuermann** [tock/tock#3308]
This issue shall serve as an overview and progress tracker for introducing IEEE 802.3 Ethernet support in Tock. If you feel there is something missing / incorrect here, feel free to leave a comment and/or edit this issue. This based on discussions at TockWorld 5 and #3103.

## Motivation

Tock already has (limited) upstream support for some communication protocols, such as Bluetooth LE, IEEE 802.15.4 with 6LoWPAN, as well as serial transports over UART & USB. Nonetheless, having at least limited support for wired Ethernet and IP in Tock seems attractive for a variety of reasons:
- Ethernet is a comparatively simple communication interface. While its high-bandwidth properties and relatively large packets may not map well to some of the smaller chips we support, it is easy to prototype networked applications on larger and Ethernet-capable boards.
- Ethernet is an accessible technology. No special hardware is required to get started (except for an Ethernet-capable supported board). This is unlike many wireless interfaces, which require secondary boards or hardware to integrate with other systems.
- Ethernet is easy to debug. Whereas wireless protocols may require specialized sniffers and debugging hardware, most Ethernet issues can be diagnosed using a regular PC and a packet sniffer application.
- Ethernet & IP can allow Tock devices to talk over the Internet and operate independently of other gateway devices or host computers. This may be especially interesting for prototyping and showcasing OTA updates.

## Approach

Developing an efficient, maintainable and virtualized (routing UDP & TCP flows to different clients) in-kernel TCP/IP stack is not trivial. Relying on pre-existing TCP/IP implementations can bridge the gap between having IP-capable Tock applications and a well-designed and functional IP stack implemented in the Tock kernel. An example for such a preexisting implementation is the [LwIP library](https://www.nongnu.org/lwip/2_1_x/index.html), released under a 3-clause BSD license. Hence I propose the following approach and scope for initial support of IEEE 802.3 Wired Ethernet and IPv6:

1. Introduce support for a set of Ethernet-capable chips and/or external Ethernet MACs (for example the ENC28J60 connected via SPI)
2. Design an Ethernet adapter HIL based on these implementations. Developing the HIL to fit multiple different chips and external MACs should make it more flexible and support a wide range of different devices.
3. Implement a system call driver, exposing a TAP-like interface to userspace (i.e., passing Ethernet frames from/to a userspace application).
4. Provide LwIP as a `libtock-c` library and supply a dummy application.

Until the Tock kernel provides a full IP stack and potentially also a TCP implementation, userspace applications utilizing preexisting network stacks like LwIP can be used to bridge the gap from application-interfaces to Ethernet MACs. It may further be feasible to implement parts of the network stack in the kernel and userspace, and cross in and out of a userspace application multiple times to process a packet.

## Steps / Issues / Pull Requests

- Ethernet-capable chip & board support / external Ethernet chips:
  - [x] Support for the [LiteEth MAC](https://github.com/enjoy-digital/liteeth) in #2203
  - [ ] Support for the QEMU RISC-V 32-bit `virt` target and VirtIO-based `NetworkDevice` (#3110)
    - [ ] The `qemu_rv32_virt` board currently requires a QEMU patch to run applications (https://lists.gnu.org/archive/html/qemu-devel/2022-09/msg01445.html).
  - [ ] ENC28J60 SPI Ethernet MAC support ([WIP capsule](https://github.com/lschuermann/tock/blob/dev/enc28j60/capsules/src/enc28j60.rs))

- [ ] Ethernet HIL: [*very* WIP on the `tock-ethernet` branch](https://github.com/tock/tock/blob/tock-ethernet/kernel/src/hil/ethernet.rs)

- [ ] Userspace TAP-like driver capsule: [WIP on the `tock-ethernet` branch](https://github.com/tock/tock/blob/tock-ethernet/capsules/src/ethernet_app_tap.rs)

- [x] LwIP support in `libtock-c`: [library on `libtock-c`'s `tock-ethernet` branch](https://github.com/tock/libtock-c/tree/tock-ethernet/lwip)
  - [ ] Simple web-server example application: [WIP on `tock-ethernet` branch](https://github.com/tock/libtock-c/blob/tock-ethernet/examples/tap_network/main.c); serves default LwIP webpage: [screenshot](https://user-images.githubusercontent.com/5341193/198919138-93b653f9-71db-4670-ac52-91add45c4b2a.png)

The current work-in-progress implementations have been successfully tested in the LiteX simulation (as pushed to `tock-ethernet`), as well as on the LiteX Arty-A7 board, as well as on an unpushed LiteX on NexysVideo board definition (can push if interesting to folks who still have it, given it was a supported OpenTitan board until recently). The most important "board" to support next is likely the QEMU RISC-V 32-bit `virt` target, as it does not depend on physical hardware and is not as complex to use as the LiteX simulator.

## Open Questions

- Can any of this re-use the existing IPv6 stack in the Tock kernel? While some of the packet processing macros can likely be reused, the existing IPv6 stack itself seems tailored towards 6LoWPAN.
- Which IP version(s) should be supported? Especially when we start to introduce IP-interfaces in the kernel, it's likely easier to support either IPv4 or IPv6 first.
- How many boards is enough to finalize the Ethernet HIL?
