### ISSUE TITLE
Make LeasableMutableBuffer Ubiqutious in the Kernel

### ISSUE THREAD

**Issue by bradjc** [tock/tock#3504]
`LeasableMutableBuffer` (and the related `LeasableBuffer`) are very useful data structures for Tock because they decouple the management and tracking of static memory (i.e. `&'static mut [u8]`) from the presentation of that memory (i.e. `buf[10..48]`). These types allow us to not lose the reference to the full static buffer, while still passing smaller buffers to various software components. I think this is very important to Tock, and a tool we should promote the use of within the kernel.

However, I see three limitations to that goal:

1. The name is too long and evokes a sense that this data structure is a special purpose tool meant to solve a very specific problem (ala `EnteredGrantKernelManagedLayout`), rather than a ubiquitous tool meant to resolve inadequacies in the rust core lib (ala `TakeCell`). It also uses too many characters in function signatures which I think sends a message not to use it.
2. The `LeasableMutableBuffer` API is incomplete. It does not provide enough functions to make the tool clearly more ergonomic than core lib tools.
3. There are not enough examples to copy from to make it easier to use.

I propose a few upgrades to `LeasableMutableBuffer`:

- [ ] Rename to `SpliceMut` and `Splice`. This evokes the expectation this is a core lib-like tool, and connects it to the rust term "slice". I expect this to be as common as "take cell" or "grant".
- [ ] Add `unslice_left()` API. This allows a lower layer to recover room to the _left_ of the existing buffer data to insert a header.
- [ ] Evaluate and potentially add various slice copy functions.
- [ ] Make it the standard for any new code that uses a `(buf: &'static mut [u8], length: usize)` tuple.
- [ ] Move the code to the `libraries` directory to reflect its status as a standard tool and not a Tock-only internal data structure.

**Comment by lschuermann** [comment]
I recently picked up work on #2637 again. This will require a very similar set of mechanical changes throughout drivers. It probably makes sense to consolidate these efforts, and to have convenient APIs for the conversion chain of `&'static mut [u8]` -> `LeasableBuffer` -> `DMABuffer` -> `LeasableBuffer` -> `&'static mut [u8]`.
