### ISSUE TITLE
Tracking: Use `start()` function in board main.rs

### ISSUE THREAD

**Issue by bradjc** [tock/tock#3518]
Since the main() function never returns, its stack frame is never reclaimed. If that stack frame is large, that results in significant stack memory waste.

We tried addressing this in #2425. However, in retrospect that was a piecemeal approach, where at the time peripheral creation was the only thing causing main's stack frame to be large. Since then, we've realized other operations cause a large stack frame (for example inlining the load_processes function #3499).

We should just avoid this once-and-for-all by moving everything that is currently in `main()` into a new function called `start()`, except for the call to `kernel::kernel_loop()`.

Boards to be updated:
- [x] acd52832 #3766
- [x] apollo3/lora_things_plus
- [x] apollo3/redboard_artemis_nano
- [x] arty_e21 #3765
- [x] clue_nrf52840 #3767
- [x] esp32-c3-devkitM-1
- [x] hail #3678 
- [x] hifive1 #3768
- [x] hifive_inventor #3768
- [x] imix #4085
- [x] imxrt1050-evkb #4085
- [x] litex/arty #4084
- [x] litex/sim #4084
- [x] microbit_v2 #3514
- [x] msp_exp432p401r #4085
- [x] nano33ble #3602 
- [x] nano_rp2040_connect #3914
- [x] nordic/nrf52840_dongle #3836
- [x] nordic/nrf52840dk #3836
- [x] nordic/nrf52dk #3836
- [x] nucleo_f429zi #3860
- [x] nucleo_f446re #3860
- [x] opentitan/earlgrey-cw310
- [x] particle_boron #3733
- [x] pico_explorer_base #3914
- [x] qemu_rv32_virt #4085
- [x] raspberry_pi_pico #3914
- [x] redboard_redv #4085
- [x] sma_q3 #4085
- [x] stm32f3discovery #4083
- [x] stm32f412gdiscovery #4083
- [x] stm32f429idiscovery #4083
- [x] swervolf #4085
- [x] teensy40  #4060
- [x] weact_f401ccu6 #4085

**Comment by twilfredo** [comment]
The Particle Boron now has support for start() fixed in https://github.com/tock/tock/pull/3733

**Comment by bradjc** [comment]
Done
