### ISSUE TITLE
Tracking: KV Stack Updates

### ISSUE THREAD

**Issue by bradjc** [tock/tock#3524]
- [x] Support kernel using kv_store
- [x] Virtualize kv_store
- [x] Change the `kv_store::set()` function to have traditional KV semantics where it will add the key/value if the key doesn't exist, or update the value if the key does exist.
- [x] Support `access_id` [permissions](https://github.com/tock/tock/blob/master/doc/TockBinaryFormat.md#7-persistent-acl) in kv_store for changing an existing key-value.
- [x] Write the top-level KV HIL we want: get/set/add/update/delete, both with permissions (aka tock header) and without.
- [ ] Provide fault tolerance: on a set, either the old key-value is present, or the new one is, but not both or neither.

**Comment by bradjc** [comment]
![2023-07-26 17 02 53](https://github.com/tock/tock/assets/1467890/9caac877-7add-4cc5-8a78-c1261cd6f6cc)

**Comment by bradjc** [comment]
Good enough for now.
