### ISSUE TITLE
Tracking: Tockbot

### ISSUE THREAD

**Issue by lschuermann** [tock/tock#3890]
#3822 introduced Tockbot, a Python script to automate some maintenance tasks in the Tock repository. This issue tracks current supported jobs and their configurations, a wishlist of new features, and known issues. Feel free to update this top posting.

## Current Features

Currently, Tockbot runs the following jobs:

- https://github.com/tock/tock/blob/b7fd5e935377f91cfc8a44b19b3fb3b9b1168067/tools/tockbot/maint_nightly.yaml#L34-L35
  For _stale_ PRs that do not have an active reviewer assigned, assign such a reviewer. For the definition of staleness, see the above task configuration.

## Wishlist

(Taken from #3822)

- [ ] mark pull requests as last-call when they've had at least one core WG member approve them, a given amount of time has passed, and no changes have been requested, (from #3822)
- [ ] ping @ tock/core-wg when a PR has been in last-call for more than 3(?) days, (from #3822)
- [ ] send out the call for agenda items with the core team call, including a list of stale PRs or PRs that have a given label (from #3822)
- [ ] ping @ tock/core-wg or create an agenda item when a PR has been blocked for a long time (e.g., every >1 month)

## Known Issues

- [ ] https://github.com/tock/tock/pull/3842 had a reviewer re-assigned, despite the PR having the "blocked" label. This should not happen as per the task-specific ignored labels: https://github.com/tock/tock/blob/b7fd5e935377f91cfc8a44b19b3fb3b9b1168067/tools/tockbot/maint_nightly.yaml#L52-L54

**Comment by bradjc** [comment]
What does it take to [assign reviewers](https://github.com/tock/tock/blob/38220da477ef5b61e2632f8b2b6ed9b9d4eda3f5/doc/wg/core/notes/core-notes-2024-03-15.md?plain=1#L20) on PR open?
