### ISSUE TITLE
Tracking: SAM4L automatic low power

### ISSUE THREAD

**Issue by alevy** [tock/tock#470]
* [x] Put cortex-m4 into deep sleep (#471)
  * [x] Add interface in chip trait to choose sleep mode (#472)
  * [x] Set deep sleep bit in SAM4L when possible (#472)
  * [x] Fix any problematic system call drivers
       1. [x] Button driver
  * [ ] Do accounting in SAM4L peripherals
       1. [x] GPIO (#472)
       2. [x] USART (#474)
       3. [x] TWIM/TWIS (~~#479~~, #761)
       4. [x] SPI (#760)
       5. [ ] ADC
       5. [ ] AES
       5. [ ] AST
       5. [ ] BPM
       5. [ ] BSCIF
       5. [ ] CRC
       5. [ ] DAC
       5. [ ] DMA
       5. [ ] Flash
       5. [ ] SCIF
       5. [ ] TRNG
       5. [ ] WDT
  * [ ] Update to new Peripheral Manager
       1. [ ] GPIO
       2. [ ] USART
       3. [x] TWIM/TWIS (#760)
       4. [x] SPI (#760)
       5. [ ] ADC
       5. [ ] AES
       5. [ ] AST
       5. [ ] BPM
       5. [ ] BSCIF
       5. [ ] CRC
       5. [ ] DAC
       5. [ ] DMA
       5. [ ] Flash
       5. [ ] SCIF
       5. [ ] TRNG
       5. [ ] WDT
  * [ ] Fast wakeup from deep sleep

**Comment by alevy** [comment]
I'm moving this tracking issue to post Tock 1.0, though we're fairly far along. @brghena and @adkinsjd did this fall off the radar, get low priority (seems like Signpost is so far holding up power-wise), or is something blocking testing/reviewing #479?

**Comment by lschuermann** [comment]
Is this still something that's worth targeting, especially given the fact that we've pivoted to nRFs as the de-facto reference boards (from SAM4L)?

**Comment by alevy** [comment]
I don't think this is even up to date. This was "solved" for Holly Chiang's EWSN '21 paper (https://www.amitlevy.com/papers/2021-ewsn-chiang.pdf). Not all of it was upstreamed as that technique was fairly invasive, but the last time this issue was even measured was well before that paper started exploring the SAM4L again.

The NRF and STM platforms are probably much more interesting in practice: the nRF doing things automatically in hardware if the kernel + apps behave well (which we know we're not necessarily hitting all those marks by default and we should probably figure out what needs doing), and the STM platforms being more similar to the SAM4L in ceding more control over power management to software.

**Comment by lschuermann** [comment]
Okay, with that I think it's appropriate to close this issue, especially given its specific to the SAM4L. If anyone wants to tackle this again we can always reopen, or we can create a low-power meta tracking issue.
