### ISSUE TITLE
Tracking: nRF52 support for Tock bootloader

### ISSUE THREAD

**Issue by niklasad1** [tock/tock#544]
Hi,
I think we should migrate to use ```tockloader``` to flash the kernel for nRF51 & nRF52.

Things that are needed:

- [x] `receive_automatic` for the nRF
- [x] flash driver that can read and write nRF flash (#942 and #935)
- [ ] some way to reset the chip from a serial connection and some way to tell the bootloader that it should stay in bootloader mode.

**Comment by alevy** [comment]
I agree. The current bootloader for the SAM4L is written using the Atmel SDK, so it wouldn't easily translate to the NRF5x. I believe the only necessary pieces to write it natively in Tock are the UART, CRC and the non-volatile memory controller. The NRF5x series doesn't seem to have a CRC controller, but we can just implement that in software (it's not ideal, but it's not so bad either).

We have all of those pieces already for the SAM4L now, so we would be able to implement a cross platform bootloader.

**Comment by bradjc** [comment]
In the current bootloader the CRC is done in software, just FYI

https://github.com/helena-project/tock-bootloader/blob/master/src/crc32.c

**Comment by bradjc** [comment]
Support for an nrf52 bootloader was just merged! It doesn't really make any sense to use it on the nrf52dk because:

1. Something on my computer corrupts messages longer than 64 bytes, which may have something to do with the serial port on mac being a "usbmodem" port and this issue: https://devzone.nordicsemi.com/f/nordic-q-a/16721/pca10040-uart-problem
2. `make flash` works over USB with no additional hardware.

So, when we have a board (likely with an ftdi chip) that needs a bootloader we can build from what we have (shouldn't take much).
