### ISSUE TITLE
Tracking: Minimize dependencies to build kernel

### ISSUE THREAD

**Issue by niklasad1** [tock/tock#866]
[thumb* support in Cargo](https://github.com/rust-lang/rust/pull/49563) is on its way which probably will help

I think it should be possible using different [workspaces](https://doc.rust-lang.org/book/second-edition/ch14-03-cargo-workspaces.html) for the different boards with separate flashing. One nice thing is that all builds will be in the same output folder

- [x] Use `rust-toolchain` file.
- [x] Remove xargo
- [x] Use LLVM LLD. (#993)
- [x] Use LLVM binutils. (#1031)
- [ ] Integrate cargo-binutils potentially to avoid a slight hack in the makefile.

**Comment by bradjc** [comment]
That was just merged. Does that mean we can get rid of xargo??

**Comment by ppannuto** [comment]
I think we'll need at least this as well: https://github.com/rust-lang/rust/issues/49380 :/

**Comment by whitequark** [comment]
That was just merged too.

**Comment by Woyten** [comment]
I already played around with Cargo's thumb* support on `libtock-rs`. Currently, I think that the quality is not good enough yet:
- https://travis-ci.org/torfmaster/libtock-rs/builds/363729498
- https://travis-ci.org/torfmaster/libtock-rs/builds/363724011

**Comment by bradjc** [comment]
I have a branch https://github.com/helena-project/tock/tree/update-nightly-2018-04-08 that updates Tock to use the nightly with those patches. However, it looks like we won't be able to actually update until rustfmt pushes a new version because some rustfmt dependencies won't compile with the new nightly.

**Comment by bradjc** [comment]
It looks like we really need this: https://github.com/rust-lang/cargo/issues/4959

**Comment by bradjc** [comment]
>To remove the need for arm-none-eabi we need: rust-lang/rust#49584

Which is now a PR: https://github.com/rust-lang/rust/pull/50336

**Comment by bradjc** [comment]
> Which is now a PR: rust-lang/rust#50336

That got merged, but then broke rust nightly for everyone. Now we are waiting on this fix: https://github.com/rust-lang/rust/pull/51703

**Comment by bradjc** [comment]
Ok fix is applied and nightlies work again. However, adding the llvm tools component doesn't seem to work.

https://github.com/rust-lang/rust/issues/49584#issuecomment-399623679

**Comment by bradjc** [comment]
We are now waiting on the very unreliable bors/travis to actually succeed

https://github.com/rust-lang/rust/pull/51728

**Comment by bradjc** [comment]
rust-lang/rust#51728 was just merged! So with tonight's nightly we should no longer need arm-none-eabi-gcc.

**Comment by bradjc** [comment]
Eh, the more I think about using cargo-binutils I don't think it is worth it. It is effectively a wrapper around the same thing we are doing now, and _adds_ a new dependency that isn't nicely version tracked as a rustup component.
