### ISSUE TITLE
Tracking: Complete move of userland to libtock-c

### ISSUE THREAD

**Issue by bradjc** [tock/tock#970]
- [x] Make sure that it is easy to program apps from the libtock-c folder for all boards.
- [x] Finish up any pull requests that would change the userland folder.
- [x] Release a version of tockloader that allows installing apps from a server. This makes it easy to get going with Tock without having to get a second repo.
- [x] Fix up any documentation in Tock that references the userland folder.
- [x] Decide what to do with the sensys course that needs a reference to libtock. (#1020)

Some of these might be addressed by tagging a release of libtock-c and just using an archive and headers directly.
