### ISSUE TITLE
Tracking: BLE Connections

### ISSUE THREAD

**Issue by alevy** [tock/tock#981]
This is a tracking issue to implement Bluetooth Low Energy connection-oriented communication for the NRF5x series.

@lindskogen's PR (#915) implemented the features necessary for the "slave role"*, but forked from a sufficiently old version of the NRF52 driver that it's very difficult to merge as-is.

Instead, we'll port over pieces of that implementation piece-meal:

(This schedule is a proposal for now)

  1. [ ] Respond to scan-requests
  2. [ ] "Catch" connection requests
  3. [ ] "Catch" first message from "master" within the connection
  4. [ ] Follow the channel hoping sequence

We should be able to implement and merge these one-by-one in the NRF5x driver, even though 2 & 3 won't be super useful until 4 is implemented.

*use of this terminology is not an endorsement
